apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghosted
  template:
    metadata:
      labels:
        app: ghosted
    spec:
      containers:
      - name: ghosted
        image: quay.io/bholifie/ghosted:latest
        ports:
        - containerPort: 7777
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghosted
  name: ghosted-service
spec:
  ports:
  - name: 7777-tcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: ghosted
  sessionAffinity: None
  type: ClusterIP
